import fs from "fs";
import path from "path";
import { antd, antdDark } from "./libs/ant-design";
import { bootstrap } from "./libs/bootstrap";
import { chakraUi } from "./libs/chakra-ui";
import { css } from "./libs/css";
import { tailwindcss } from "./libs/tailwindcss";
import { LibData } from "./types";

const distDir = "dist";

console.time("timer");

const libs: LibData[] = [bootstrap, chakraUi, tailwindcss, antd, antdDark, css];

const template = ({
  name,
  website,
  colors,
}: {
  name: string;
  website: string;
  colors: any;
}) => {
  return `/**
* File generated by webcolors-factory
* ${new Intl.DateTimeFormat("en-US", {
    dateStyle: "long",
    timeStyle: "long",
  }).format(new Date())}
* Copyright from ${name}, ${website},
*/
const colors = ${JSON.stringify(colors, null, 2)};
export default colors;
`;
};

libs.forEach((lib) => {
  fs.writeFile(path.join(distDir, `${lib.slug}.js`), template(lib), function (
    err
  ) {
    if (err) throw err;
    console.log(`🎨 File ${lib.slug}.js created.`);
  });
});
console.timeEnd("timer");
